export const Users = [
  {
    id: 1,
    org: "AB株式会社",
    profilePicture: "assets/person/1.jpeg",
    username: "akihisa",
  },
  {
    id: 2,
    org: "株式会社CDE",
    profilePicture: "assets/person/2.jpeg",
    username: "terakado",
  },
  {
    id: 3,
    org: "早計大学総合病院",
    profilePicture: "assets/person/3.jpeg",
    username: "Koga",
  },
  {
    id: 4,
    org: "ICUクリニック",
    profilePicture: "assets/person/4.jpeg",
    username: "Matukubo",
  },
  {
    id: 5,
    org: "ZY病院",
    profilePicture: "assets/person/5.jpeg",
    username: "Kikukawa",
  },
];

export const Posts = [
  {
    id: 1,
    org: "AB株式会社",
    desc: "医療機器管理のSaaSを導入しております。もし利用されたい方いらっしゃれば、ぜひご連絡ください。",
    photo: "assets/post/1.jpeg",
    date: "5分前",
    userId: 1,
    like: 20,
    comment: 4,
  },
  {
    id: 2,
    org: "AB株式会社",
    desc: "医療文書管理を横断してできるツールを開発しております。ご興味あれば導入いたします。",
    photo: "assets/post/2.jpeg",
    date: "2分前",
    userId: 2,
    like: 140,
    comment: 13,
  },
  {
    id: 3,
    org: "早計大学総合病院",
    desc: "科ごとの意思決定が分かれているのに、患者の管理が一括管理できていない。同意書が複数あり、煩雑になっている。",
    photo: "assets/post/3.jpeg",
    date: "10分前",
    userId: 3,
    like: 230,
    comment: 29,
  },
  {
    id: 4,
    org: "ICUクリニック",
    desc: "患者の毎月のデータと処方箋の売り上げ管理を一元化したい。",
    photo: "assets/post/4.jpeg",
    date: "1分前",
    userId: 4,
    like: 10,
    comment: 1,
  },
  {
    id: 5,
    org: "ZY病院",
    desc: "診断時の会話を録音したり、ドキュメント化を自動化してコアな業務に集中したいのですが、良いツールはありませんか。",
    photo: "assets/post/5.jpeg",
    date: "1分前",
    userId: 5,
    like: 100,
    comment: 3,
  },
];